### PR TITLE
supportable immutable puts

### PR DESCRIPTION
**Pull request by mafintosh**

### CODE REVIEW

**Comment by pfrazee** [comment]
Well that's interesting, what prompted this?

**Comment by mafintosh** [comment]
Need it for a quick sync tool. This is the first step for a full compare and swap api

**Comment by pfrazee** [comment]
Does it create entries that can't be overwritten or deleted, or is this something more subtle and internal?

**Comment by mafintosh** [comment]
It's just skips writing a new entry if it's already there (ie it's an immutable write). Undocumented because it'll prob change quite a bit later on.

**Comment by andrewosh** [comment]
Looks fine so long as it's not part of the public API. If it were, I don't think the option should be called `immutable` -- sounds like immutability is persisted during the write.

**Review by andrewosh — APPROVED** [review]

**Comment by mafintosh** [comment]
Changing the name to overwrite: false

**Pull request merged**
